#
# Copyright (C) 2021-2022 The Android Open Source Project
# Copyright (C) 2022 SebaUbuntu's TWRP device tree generator
# Copyright (C) 2022 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

include device/orangepi/common/BoardConfigCommon.mk


BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

DEVICE_PATH := device/orangepi/apollo
DEVICE_DIR_PLUS := $(DEVICE_PATH)/apollo-p2

# Platform
BOARD_VENDOR := Allwinner
TARGET_BOARD_PLATFORM := apollo
TARGET_BOARD_PLATFORM_GPU := mali-g31
TARGET_ENFORCES_QSSI := true
TARGET_PLATFORM := homlet
$(call soong_config_add,vendor,board,$(TARGET_BOARD_PLATFORM))
$(call soong_config_add,vendor,platform,$(TARGET_PLATFORM))
$(call soong_config_add,widevine,cryptolevel,$(BOARD_WIDEVINE_OEMCRYPTO_LEVEL))

TARGET_BOARD_KERN_VER := 5.4
TARGET_BOARD_CHIP := sun50iw9p1
TARGET_BOARD_IC := h618
PRODUCT_BOARD := p2
TARGET_BOOTLOADER_BOARD_NAME := exdroid
TARGET_BOOTLOADER_NAME := exdroid
TARGET_OTA_RESTORE_BOOT_STORAGE_DATA := true

# Enable dex-preoptimization to speed up first boot sequence
WITH_DEXPREOPT := true
DONT_DEXPREOPT_PREBUILTS := false
TARGET_USE_NEON_OPTIMIZATION := true

TARGET_CPU_SMP := true

#Reserve0
BOARD_ROOT_EXTRA_FOLDERS += Reserve0

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7

#TARGET_2ND_ARCH := arm
#TARGET_2ND_ARCH_VARIANT := armv7-a-neon
#TARGET_2ND_CPU_ABI := armeabi-v7a
#TARGET_2ND_CPU_ABI2 := armeabi
#TARGET_2ND_CPU_VARIANT := generic
TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_32_BIT_APPS := true
TARGET_USES_G2D := true
WRITE_BACK_MODE := 0
$(call soong_config_add,disp,writebackMode,$(WRITE_BACK_MODE))

TARGET_USES_MKE2FS := true

BOARD_USES_RECOVERY_AS_BOOT := true
TARGET_NO_RECOVERY := true

# Assert
TARGET_OTA_ASSERT_DEVICE := apollo

BOARD_ADD_PACK_CONFIG += $(DEVICE_DIR_PLUS)/system/sys_partition.fex
BOARD_ADD_PACK_CONFIG += $(DEVICE_PATH)/common/system/env.cfg
BOARD_ADD_PACK_CONFIG += $(DEVICE_DIR_PLUS)/system/dragon_toc.cfg

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_ALGORITHM := SHA256_RSA2048
BOARD_AVB_KEY_PATH := vendor/security/toc_keys/SCPFirmwareContentCertPK.pem

# Using sha256 for dm-verity partitions.
# product, vendor_dlkm
BOARD_AVB_PRODUCT_ADD_HASHTREE_FOOTER_ARGS += --hash_algorithm sha256
BOARD_AVB_VENDOR_DLKM_ADD_HASHTREE_FOOTER_ARGS += --hash_algorithm sha256

BOARD_AVB_VBMETA_SYSTEM := system
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := vendor/security/toc_keys/SCPFirmwareContentCertPK.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_SYSTEM_ADD_HASHTREE_FOOTER_ARGS += --hash_algorithm sha256

BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := vendor/security/toc_keys/SCPFirmwareContentCertPK.pem
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 2
BOARD_AVB_VENDOR_ADD_HASHTREE_FOOTER_ARGS += --hash_algorithm sha256

BOARD_AVB_RECOVERY_KEY_PATH := vendor/security/toc_keys/SCPFirmwareContentCertPK.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA2048
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 3


# boot
BOARD_BOOT_HEADER_VERSION ?= 3
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
ifeq ($(PRODUCT_BUILD_VENDOR_BOOT_IMAGE),true)
    BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 33554432
    # BOARD_VENDOR_RAMDISK_KERNEL_MODULES will copied to vendor-ramdisk/lib/modules
    BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
        $(patsubst %.ko,$(PRODUCT_PREBUILT_PATH)/dist/%.ko,$(shell cat $(DEVICE_DIR_PLUS)/system/vendor_ramdisk.modules | sed 's/^\s\+//g;s/\s\+$$//g;/^#/d;/^$$/d'))
endif

BOARD_USES_VENDORIMAGE := true

# Camera
PRODUCT_HAS_UVC_CAMERA := true

# Graphics
TARGET_USES_HWC2 := true

MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024

#BOARD_INCLUDE_DTB_IN_VENDOR_BOOT := true
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
#BOARD_VENDOR_BOOTIMAGE_DTB := $(PRODUCT_OUT)/dtb.img

#BOARD_MKBOOTIMG_ARGS += --dtb $(PRODUCT_OUT)/dtb.img

# File systems
#BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
#TARGET_COPY_OUT_SYSTEM := system
TARGET_RECOVERY_FSTAB_IN_VENDOR_RAMDISK := true
#BOARD_HAS_LARGE_FILESYSTEM := true
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_CACHEIMAGE_PARTITION_SIZE := 0
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_HAS_NO_CACHE_PARTITION := true
BOARD_DTBOIMG_PARTITION_SIZE := 2097152
BOARD_PREBUILT_DTBOIMAGE := $(PRODUCT_PREBUILT_PATH)/dtbo.img
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x04000000
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1146880000
#BOARD_VENDORIMAGE_PARTITION_SIZE := 110854144
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 4096
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USES_METADATA_PARTITION ?= true

# Enable SVELTE malloc
MALLOC_SVELTE := true

# HIDL
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml
DEVICE_MATRIX_FILE := $(DEVICE_PATH)/common/system/compatibility_matrix.xml
DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE=$(DEVICE_PATH)/common/system/compatibility_matrix_product.xml
#TARGET_FS_CONFIG_GEN := $(DEVICE_PATH)/config.fs

# Kernel
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
BOARD_KERNEL_CMDLINE += androidboot.dtbo_idx=0,1,2
BOARD_KERNEL_CMDLINE += firmware_class.path=/vendor/etc/firmware

BOARD_INCLUDE_RECOVERY_DTBO := true
#BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_KERNEL_DTB_OVERLAYS := $(wildcard $(DEVICE_PATH)/dtbo/h618/dtbo/*.dtbo)
BOARD_BOOTIMG_HEADER_VERSION := 3
BOARD_KERNEL_ARCH := arm64
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00080000
BOARD_RAMDISK_OFFSET := 0x03400000
BOARD_KERNEL_TAGS_OFFSET := 0x01e00000
BOARD_DTB_OFFSET := 0x03300000
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_MKBOOTIMG_ARGS += --board $(BOARD_KERNEL_ARCH) --kernel_offset $(BOARD_KERNEL_OFFSET) --dtb_offset $(BOARD_DTB_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/orangepi/apollo
TARGET_KERNEL_CONFIG := lineageos_apollo_defconfig
TARGET_KERNEL_VERSION := 5.4
BOARD_KERNEL_VERSION := 5.4
BOARD_KERNEL_PATCHLEVEL := 4

BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true
BOARD_SUPER_IMAGE_IN_UPDATE_PACKAGE := true
BOARD_SUPER_PARTITION_SIZE := 3221225472
BOARD_SUPER_PARTITION_GROUPS := sb
BOARD_SB_SIZE := $(shell expr $(BOARD_SUPER_PARTITION_SIZE) - 8388608)
BOARD_SB_PARTITION_LIST := system vendor product vendor_dlkm

TARGET_USERIMAGES_USE_F2FS ?= true

# Treble
BOARD_VNDK_VERSION := current

# product.img
BOARD_USES_PRODUCTIMAGE := true
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_PRODUCT := product

# Build a separate vendor_dlkm.img partiton
BOARD_USES_VENDOR_DLKMIMAGE := true
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

# Vendor files
#include vendor/samsung/apollo/BoardConfigVendor.mk

# wifi and bt configuration
# 1. Wifi Configuration
BOARD_WIFI_VENDOR := common
BOARD_USR_WIFI    :=
WIFI_DRIVER_MODULE_PATH :=
WIFI_DRIVER_MODULE_NAME :=
WIFI_DRIVER_MODULE_ARG  :=

# 2. Bluetooth Configuration
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_VENDOR    := common
BOARD_HAVE_BLUETOOTH_NAME :=
BOARD_BLUETOOTH_CONFIG_DIR :=  device/orangepi/apollo/common/wireless/bluetooth
BOARD_BLUETOOTH_TTY := /dev/ttyAS1
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/orangepi/apollo/common/wireless/bluetooth
# Must include after wifi/bt configuration
include device/orangepi/common/config/wireless/wireless_config.mk

USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 2
TARGET_USES_HWC2 := true
TARGET_GPU_TYPE := mali-g31
USE_IOMMU := true

# ensure metadata uses 256 inode (avoit 2038 warning)
BOARD_METADATAIMAGE_MKFS_OPTIONS := -I 256


include hardware/aw/gpu/product_config.mk
include vendor/aw/homlet/HomletBoardConfig.mk
